title: "Yannock Verne"
description: "Streamer, Imperial Geographic, photographe du Verse & SubOrbital Records."
url: "https://yannockverne.github.io"
baseurl: ""

# ----------- THEME -----------
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

sass:
  style: compressed
# ----------- NAVIGATION -----------
include:
  - _pages
  - assets/css/custom.css
# ----------- DEFAULT CONFIG FOR PAGES -----------
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar: false
      author_profile: false
      toc: false

# ----------- BUILD -----------
markdown: kramdown