title: "Yannock / Yannock Verne"
description: "Streamer, Ã©diteur ImpGeo, photographe du Verse & fondateur de SubOrbital Records."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# URL : remplace par ton user et repo
url: "https://yannockverne.github.io"
baseurl: ""  # laisse vide ("") si c'est ton user.github.io

author:
  name: "Yannock Verne"
  email: ""  # optionnel

# Navigation principale
header_pages:
  - index.md
  - twitch.md
  - impgeo.md
  - photo.md
  - suborbital.md
